# Generated by Django 5.0.7 on 2024-07-31 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviapp', '0002_bookings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
