# Generated by Django 5.0.7 on 2024-07-31 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviapp', '0005_bookings_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='time',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moviapp.time'),
        ),
    ]
